name: Demo Action Harness
description: 'Greet someone and record the time'
author: Ediz Ertekin Jr
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

outputs:
  time: # id of output
    description: 'The time we greeted you'
branding:
  icon: 'anchor'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
